home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('skills', views.skills, name='skills'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/home.html')

def skills(request):
    return render(request, 'home/skills.html')

home/templates/home/base.html
    <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #74c69d">
      <a class="navbar-brand">Welcome!</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'home:index'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'home:skills'%}">Skills</a>
          </li>
        </ul>
      </div>
    </nav>

home/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <title>Welcome</title>
  </head>

  <body>
  {% include 'home/base.html' %}
    <div class="d-flex flex-column my-flex-container2">
      <div class="image">
        <img src="\static\home\images\FR36.jpg" alt="ini foto" width="230" height="350">
      </div>
      <div>
      <table border="0px" id="spaces">
        <tbody>
                <tr>
                    <td>
                        <a href=https://twitter.com/grassterra>
                            <img src="\static\home\images\twitter.png" alt="twatter" width="50" height="50">
                        </a>
                    </td>
                    <td>
                        <a href=https://steamcommunity.com/id/grassterra>
                            <img src="\static\home\images\steam.png" alt="stim" width="50" height="50"> 
                        </a>
                    </td>
                    <td>
                        <a href=https://www.instagram.com/grassterra/>
                            <img src="\static\home\images\instagram.png" alt="dead social media" width="50" height="50">
                        </a>
                    </td>
                    <td>
                        <a href=https://gitlab.com/Grassterra>
                            <img src="\static\home\images\gitlab.png" alt="stim" width="50" height="50"> 
                        </a>
                    </td>
        </tbody>
      </table>
      </div>
    </div>
    <div class="d-flex flex-column my-flex-container">
      <h2>Hello!</h2>
      <div class="p-2 my-flex-item">I'm Muhammad Aditya Pratama Dungga, and usually called Adit. Currently, I’m a Sophomore at University of Indonesia, majoring in Information System. I also have an interest in Gacha Games.</div>
      <div>
      <table border="2px solid black">
            <tbody>
                <tr id="id1">
                    <td rowspan='4'>Education History</td>
                    <td>SDIT Sabilina</td>
                <tr id="id1">
                    <td>SMPI Al-Azhar 19</td>
                <tr id="id1">
                    <td>SMAN 48 Jakarta</td>
                <tr id="id1">
                    <td>University of Indonesia</td>
            </tbody>
        </table>
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/skills.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">

    <title>My Skills</title>
  </head>

   <body>
    {% include 'home/base.html' %}
    <div class="d-flex flex-row justify-content-between my-flex-container3">
        <div class="my-flex-item">
            <div class="image" id="justify"><img src="\static\home\images\Python.png" width="200" height="200" style="center"></div>
            <div id="justify"> I can do basic programming with Python and Java language.</div>
        </div>
        <div class="my-flex-item" >
            <div class="image" id="justify"><img src="\static\home\images\fight.png" width="200" height="200"></div>
            <div id="justify"> Brawlhalla's top 0.7% player, ranked 65th on last SEA Summer Championship.</div>
        </div>
        <div class="my-flex-item">
            <div class="image" id="justify"><img src="\static\home\images\music.png" width="200" height="200"></div>
            <div id="justify"> Able to play most band's instrument, especially Bass. I can also compose some simple music.</div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>